In [9]:
import numpy as np
import pyvista as pv
pv.start_xvfb()

In [2]:
arr = np.load("/home/aleksandr/data/local-bucket/preprocessed_bedrooms/f5ee5167-b1c2-4fb2-86b4-5f5b609fe371_Bedroom-12315/boxes.npz")

In [6]:
for f in arr.files:
    print(f, arr[f])

uids ['2021159370842042461888/model' '2021159370842042548000/model'
 '2021159370842042583296/model']
jids ['9a967b96-b40c-486a-ba68-e6183fd07575'
 'c68d16c3-982d-4dba-85fd-a6a1414f7341'
 '58fabe3e-ceb0-4886-a702-45a948d0af2e']
scene_id Bedroom-12315
scene_uid f5ee5167-b1c2-4fb2-86b4-5f5b609fe371_Bedroom-12315
scene_type bedroom
json_path f5ee5167-b1c2-4fb2-86b4-5f5b609fe371
room_layout [[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]]
floor_plan_vertices [[ 3.1248   0.      -2.8782 ]
 [ 2.40876  0.      -2.8109 ]
 [ 2.40876  0.      -2.8782 ]
 ...
 [ 1.50676  0.      -5.5802 ]
 [ 1.50776  0.      -5.6485 ]
 [ 1.50776  0.      -5.5792 ]]
floor_plan_faces [[  0   2   1]
 [  3   5   4]
 [  6   8   7]
 [  9  11  10]
 [ 12  14  13]
 [ 15  17  16]
 [ 18  20  19]
 [ 21  23  22

In [7]:
arr2 = np.load("/home/aleksandr/data/local-bucket/preprocessed_bedrooms/ffd98024-7200-429e-8b9a-1234a5937826_MasterBedroom-118/boxes.npz")

In [8]:
for f in arr2.files:
    print(f, arr2[f])

uids ['780/model' '781/model' '786/model']
jids ['f0b346ac-4c07-4fde-8eff-9c3537304525'
 '6a0b1325-4b16-4fd2-9f42-2742a8f8ca6f'
 'cdbee3f3-750f-49f7-9cb4-167c7788b522']
scene_id MasterBedroom-118
scene_uid ffd98024-7200-429e-8b9a-1234a5937826_MasterBedroom-118
scene_type masterbedroom
json_path ffd98024-7200-429e-8b9a-1234a5937826
room_layout [[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]]
floor_plan_vertices [[-0.7193  0.     -1.0673]
 [-2.4496  0.      0.9288]
 [-2.4496  0.     -1.0673]
 [-2.4496  0.      0.9288]
 [-0.7193  0.     -1.0673]
 [ 1.5079  0.      0.9288]
 [ 1.5079  0.      0.9288]
 [-0.7193  0.     -1.0673]
 [ 1.5079  0.     -1.0673]
 [ 1.5079  0.      0.9288]
 [ 1.5079  0.     -1.0673]
 [ 1.5079  0.     -0.8552]]
floor_plan_faces [[ 0  2  1]
 [ 3  5  4]

In [ ]:
obj = pv.PolyData(arr2["floor_plan_vertices"], arr2["floor_plan_faces"])
obj.plot()

: 

: 